# Generated by Django 3.1.7 on 2021-08-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academicyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyearname', models.CharField(blank=True, max_length=255, null=True)),
                ('startson', models.DateField(blank=True, null=True)),
                ('endson', models.DateField(blank=True, null=True)),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchname', models.CharField(max_length=255)),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('academicid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituteApp.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('isactive', models.BooleanField(blank=True, default=True, null=True)),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('academicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Quata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdmittedQuata', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabus/')),
                ('academicid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituteApp.academicyear')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituteApp.batch')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituteApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('Experience', models.IntegerField()),
                ('Gender', models.CharField(max_length=255)),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('starttime', models.CharField(max_length=255)),
                ('endtime', models.CharField(max_length=255)),
                ('isbreak', models.BooleanField(blank=True, default=False, null=True)),
                ('batchname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.batch')),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissionnumber', models.CharField(blank=True, max_length=220, null=True)),
                ('admissionyear', models.CharField(blank=True, max_length=220, null=True)),
                ('firstname', models.CharField(blank=True, max_length=220, null=True)),
                ('lastname', models.CharField(blank=True, max_length=220, null=True)),
                ('email', models.CharField(blank=True, max_length=220, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=220, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('contactdetails', models.CharField(blank=True, max_length=220, null=True)),
                ('gender', models.CharField(blank=True, max_length=220, null=True)),
                ('rollno', models.IntegerField(blank=True, null=True)),
                ('attend', models.CharField(blank=True, max_length=255, null=True)),
                ('regno', models.IntegerField(blank=True, null=True)),
                ('academicyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituteApp.academicyear')),
                ('admittedquota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituteApp.quata')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituteApp.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituteApp.course')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='courseid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.course'),
        ),
        migrations.CreateModel(
            name='AssignTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.teacher')),
                ('academicyearname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instituteApp.academicyear')),
                ('batchname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.batch')),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instituteApp.subject')),
            ],
        ),
    ]
