# Generated by Django 3.1.3 on 2020-11-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academicyear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyearname', models.CharField(blank=True, max_length=255, null=True)),
                ('startson', models.DateField(blank=True, null=True)),
                ('endson', models.DateField(blank=True, null=True)),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('isactive', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('isactive', models.BooleanField(blank=True, default=True, null=True)),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('academicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=255)),
                ('academicid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Designation', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('Experiance', models.IntegerField()),
                ('Gender', models.CharField(max_length=255)),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabus/')),
                ('academicid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academicyear')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchname', models.CharField(max_length=255)),
                ('addondate', models.DateTimeField(auto_now_add=True)),
                ('updateddate', models.DateTimeField(auto_now=True)),
                ('academicid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academicyear')),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssignTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
                ('academicyearname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academicyear')),
                ('batchname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.batch')),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
            ],
        ),
    ]
